
ALTER TABLE `campus` CHANGE `id` `id` INT(11) NOT NULL AUTO_INCREMENT; 

INSERT INTO `auth_modules` (`id`, `name`, `default_url`, `module_name`, `icon_class`, `parent_id`, `have_child`, `allowed_permissions`, `sorting`, `is_visible`, `detail`, `is_enable`, `created_at`, `updated_at`, `created_by`, `updated_by`, `deleted_at`) VALUES ('59', 'Campus Modules', 'campus_setup', NULL, 'mdi mdi-folder-multiple-outline', '0', '1', NULL, '1', '1', '0', '1', '2021-08-20 12:00:54', NULL, NULL, NULL, NULL); 
INSERT INTO `auth_modules` (`id`, `name`, `default_url`, `module_name`, `icon_class`, `parent_id`, `have_child`, `allowed_permissions`, `sorting`, `is_visible`, `detail`, `is_enable`, `created_at`, `updated_at`, `created_by`, `updated_by`, `deleted_at`) VALUES ('60', 'Session Assign', 'campus_setup/session_assign', NULL, 'mdi mdi-folder-multiple-outline', '59', '0', '{\"POST\":\"Add\",\"PUT\":\"Update\",\"GET\":\"View\",\"DELETE\":\"Remove\"}', '1', '1', '1', '1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `auth_modules` ( `id`, `name`, `default_url`, `module_name`, `icon_class`, `parent_id`, `have_child`, `allowed_permissions`, `sorting`, `is_visible`, `detail`, `is_enable`, `created_at`, `updated_at`, `created_by`, `updated_by`, `deleted_at` ) VALUES ( '61', 'Class Assign', 'campus_setup/class_assign', NULL, 'mdi mdi-folder-multiple-outline', '59', '0', '{\"POST\":\"Add\",\"PUT\":\"Update\",\"GET\":\"View\",\"DELETE\":\"Remove\"}', '1', '1', '1', '1', NULL, NULL, NULL, NULL, NULL ) ;

INSERT INTO `users` (`id`, `keycloak_id`, `role_id`, `username`, `firstName`, `lastName`, `full_name`, `password`, `phone`, `email`, `address`, `user_type`, `is_enable`, `created_at`, `updated_at`, `created_by`, `updated_by`, `deleted_at`) VALUES (NULL, 'f59a9deb-1db9-4faa-a949-0e7915246b54', '17', 'superadmin_it', NULL, NULL, 'superadmin_it', NULL, '00000000000', 'superadmin@it.com', '', '1', '1', '2021-08-27 12:24:21', '2021-08-20 13:45:59', '1', '1', NULL);

INSERT INTO `auth_modules` (`id`, `name`, `default_url`, `module_name`, `icon_class`, `parent_id`, `have_child`, `allowed_permissions`, `sorting`, `is_visible`, `detail`, `is_enable`, `created_at`, `updated_at`, `created_by`, `updated_by`, `deleted_at`) VALUES (NULL, 'Fee Type', 'setup/feetype', NULL, 'mdi mdi-folder-multiple-outline', '15', '0', '{\"POST\":\"Add\",\"PUT\":\"Update\",\"GET\":\"View\",\"DELETE\":\"Remove\"}', '1', '1', '1', '1', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO `auth_modules` (`id`, `name`, `default_url`, `module_name`, `icon_class`, `parent_id`, `have_child`, `allowed_permissions`, `sorting`, `is_visible`, `detail`, `is_enable`, `created_at`, `updated_at`, `created_by`, `updated_by`, `deleted_at`) VALUES (NULL, 'Admission Type', 'setup/admissiontype', NULL, 'mdi mdi-folder-multiple-outline', '15', '0', '{\"POST\":\"Add\",\"PUT\":\"Update\",\"GET\":\"View\",\"DELETE\":\"Remove\"}', '1', '1', '1', '1', NULL, NULL, NULL, NULL, NULL); 
INSERT INTO `auth_modules` (`id`, `name`, `default_url`, `module_name`, `icon_class`, `parent_id`, `have_child`, `allowed_permissions`, `sorting`, `is_visible`, `detail`, `is_enable`, `created_at`, `updated_at`, `created_by`, `updated_by`, `deleted_at`) VALUES (NULL, 'Discount Type', 'setup/discount_type', NULL, 'mdi mdi-folder-multiple-outline', '15', '0', '{\"POST\":\"Add\",\"PUT\":\"Update\",\"GET\":\"View\",\"DELETE\":\"Remove\"}', '1', '1', '1', '1', NULL, NULL, NULL, NULL, NULL); 
