-- <Ameesh>

ALTER TABLE `campus_section` DROP COLUMN `organization_id`, DROP COLUMN `countries_id`, DROP COLUMN `state_id`, DROP COLUMN `region_id`, DROP COLUMN `city_id`, DROP INDEX `campus_section_organization_id_foreign`, DROP INDEX `campus_section_countries_id_foreign`, DROP INDEX `campus_section_state_id_foreign`, DROP INDEX `campus_section_region_id_foreign`, DROP INDEX `campus_section_city_id_foreign`, DROP FOREIGN KEY `campus_section_city_id_foreign`, DROP FOREIGN KEY `campus_section_countries_id_foreign`,DROP FOREIGN KEY `campus_section_organization_id_foreign`, DROP FOREIGN KEY `campus_section_region_id_foreign`, DROP FOREIGN KEY `campus_section_state_id_foreign`;
ALTER TABLE `campus_session` DROP COLUMN `organization_id`, DROP COLUMN `countries_id`, DROP COLUMN `state_id`, DROP COLUMN `region_id`, DROP COLUMN `city_id`, DROP INDEX `campus_session_organization_id_foreign`, DROP INDEX `campus_session_countries_id_foreign`, DROP INDEX `campus_session_state_id_foreign`, DROP INDEX `campus_session_region_id_foreign`, DROP INDEX `campus_session_city_id_foreign`, DROP FOREIGN KEY `campus_session_city_id_foreign`, DROP FOREIGN KEY `campus_session_countries_id_foreign`, DROP FOREIGN KEY `campus_session_organization_id_foreign`, DROP FOREIGN KEY `campus_session_region_id_foreign`, DROP FOREIGN KEY `campus_session_state_id_foreign`; 
ALTER TABLE `designation` ADD COLUMN `department_id` INT(11) NOT NULL AFTER `organization_id`;
ALTER TABLE `campus_seating_capacity` DROP COLUMN `organization_id`, DROP COLUMN `countries_id`, DROP COLUMN `state_id`, DROP COLUMN `region_id`, DROP COLUMN `city_id`, DROP COLUMN `session_id`, DROP INDEX `campus_seating_capacity_organization_id_foreign`, DROP INDEX `campus_seating_capacity_countries_id_foreign`, DROP INDEX `campus_seating_capacity_state_id_foreign`, DROP INDEX `campus_seating_capacity_region_id_foreign`, DROP INDEX `campus_seating_capacity_city_id_foreign`, DROP INDEX `campus_seating_capacity_session_id_foreign`, DROP FOREIGN KEY `campus_seating_capacity_city_id_foreign`, DROP FOREIGN KEY `campus_seating_capacity_countries_id_foreign`, DROP FOREIGN KEY `campus_seating_capacity_organization_id_foreign`, DROP FOREIGN KEY `campus_seating_capacity_region_id_foreign`, DROP FOREIGN KEY `campus_seating_capacity_session_id_foreign`, DROP FOREIGN KEY `campus_seating_capacity_state_id_foreign`; 


-- </Ameesh>
